<?php
$this->title = "Editar Perfil";
$this->headTitle($this->title);
?>
<div id="enteo-page">
    <div id="ctn-content">
        <?php echo $this->render('left-cliente.phtml') ?>
        <div class="center">
            <p class="sidebar-title">
                <img src="/images/guardar.png">
                Editar Perfil
            </p>
            <div>
                <?php echo $this->form ?>
            </div>
        </div>
    </div>
</div>