<?php
$this->title = "Registrarse";
$this->headTitle($this->title);
?>
<div id="enteo-page">
    <div id="ctn-content">
        <center>
            <p class="sidebar-title" style="margin-left: -47px">
                <img src="/images/guardar.png">
                Registrarse
            </p>
        </center>

        <div style="width:800px;margin-left: 90px;">
            <?php echo $this->form; ?>
        </div>

    </div>
</div>