<?php
$this->title = "Contactanos";
$this->headTitle($this->title);
?>
<div class="center">
    <div>
        <center>
            <a href="" rel="_blank" target="_self">
                <img src="/images/contacto_contacto.png" width="750" height="100" alt="contacto">
            </a>
        </center>
    </div>
    <div class="div_form">
        <form method="Post" action="/contacto" style="width: 100%; height: 670px; margin-left:-2%">
            <table >
                <tbody>
                    <tr style="width: 66%; margin-left:0%">
                        <td>Nombre</td>
                        <td style="margin-top: 32px;padding-bottom: 28px;padding-top: 0px;"><?php echo $this->formuluario->getElement('nombre'); ?></td>
                    </tr>  
                    <tr style="width: 66%; margin-left:0%">
                        <td>Email</td>
                        <td style="margin-top: 32px;padding-bottom: 28px;padding-top: 0px;"><?php echo $this->formuluario->getElement('email'); ?></td>
                    </tr>
                    <tr style="width: 66%; margin-left:0%">
                        <td>Mensaje</td>
                        <td style="margin-top: 32px;padding-bottom: 28px;padding-top: 0px;"><?php echo $this->formuluario->getElement('mensaje'); ?></td>
                    </tr>
                    <tr style="width: 66%; margin-left:0%; margin-top: -26px">
                        <td></td>
                        <td onclick="alert('Su mensaje ha sido enviado, lo responderemos lo antes posible... Gracias')"> <?php echo $this->formuluario->getElement('Enviar'); ?> </td>

                    </tr>
                </tbody>

            </table>

            <div class="mapa">
                <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.cl/maps?f=q&amp;source=s_q&amp;hl=es-419&amp;geocode=&amp;q=Camino+San+Antonio+1085+,+vi%C3%B1a+del+mar&amp;aq=t&amp;sll=-33.012316,-71.543033&amp;sspn=0.009842,0.021136&amp;ie=UTF8&amp;hq=&amp;hnear=San+Antonio+1085,+Vi%C3%B1a+del+Mar,+Valpara%C3%ADso&amp;ll=-33.012316,-71.543033&amp;spn=0.00977,0.021136&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.cl/maps?f=q&amp;source=embed&amp;hl=es-419&amp;geocode=&amp;q=Camino+San+Antonio+1085+,+vi%C3%B1a+del+mar&amp;aq=t&amp;sll=-33.012316,-71.543033&amp;sspn=0.009842,0.021136&amp;ie=UTF8&amp;hq=&amp;hnear=San+Antonio+1085,+Vi%C3%B1a+del+Mar,+Valpara%C3%ADso&amp;ll=-33.012316,-71.543033&amp;spn=0.00977,0.021136&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>

            </div>
            <div class="div_horario">
                <h2>Horario de Atención</h2>
                <p style="margin-top: -18px">Lunes a sábado desde las 9:30 am hasta las 23:30 pm </p><br><p style="margin-top: -60px">(horario continuado)</p>
            </div>


        </form>
    </div>


</div>