<?php
$this->title = "Agregar Venta";
$this->headTitle($this->title);
?>
<div id="enteo-page">
    <div id="ctn-content">
        <?php echo $this->render('left-admin.phtml') ?>
        <div class="center">
            <p class="sidebar-title">
                <img src="/images/guardar.png">
                Agregar Venta
            </p>
            <center>
                <?php echo $this->form; ?>
            </center>
        </div>
    </div>
</div>

