<?php
$this->title = "Agregar Menu";
$this->headTitle($this->title);
?>
<div id="enteo-page">
    <div id="ctn-content">
        <?php echo $this->render('left-admin.phtml') ?>
        <div class="center">
            <p class="sidebar-title">
                <img src="/images/guardar.png">
                Crear Menu
            </p>
            <?php echo $this->formuluario; ?>
        </div>
    </div>
</div>