<?php
$this->title = "Agregar Cliente";
$this->headTitle($this->title);
?>
<div id="enteo-page">
    <div id="ctn-content">
        <?php echo $this->render('left-admin.phtml') ?>

        <div class="center">

            <p class="sidebar-title">
                <img src="/images/guardar.png">
                Añadir Cliente
            </p>
            <?php echo $this->formuluario; ?>


        </div>
    </div>
</div>