<?php
$this->title = "Agregar Tipo Prodcuto";
$this->headTitle($this->title);
?>
<div id="enteo-page">
    <div id="ctn-content">
        <?php echo $this->render('left-admin.phtml') ?>
        <div class="center">

            <p class="sidebar-title">
                <img src="/images/guardar.png">
                Agregar Tipo Publicacion
            </p>
            <?php echo $this->form; ?>
            
            
            
        </div>
    </div>
</div>
