<?php
$this->title = "Administracion";
$this->headTitle($this->title);
?>
<div id="enteo-page">
    <div id="ctn-content">
        <?php echo $this->render('left-admin.phtml') ?>
        <div class="center">
            <div id="ctn-slider">
                <p class="sidebar-title"><img src="/images/guardar.png"> Panel Administración </p>
                <div class="bottones-principales">
                    <a   href="/administrador/agregarventa" target="_self">
                        <img src="/images/Btn_agregar_venta.png" width="126" height="160" alt="Agregar Venta">
                    </a>
                    <a  class="" href="/administrador/agregarcliente"  target="_self">
                        <img src="/images/Btn_agregar_cliente2.png" width="126" height="160" alt="Agregar Cliente">
                    </a>
                    <a href="/administrador/agregarmenu"  target="_self">
                        <img src="/images/Btn_agregar_menu2.png" width="126" height="160" alt="Agregar Menu">
                    </a>
                    <a href="/administrador/agregarproducto"  target="_self">
                        <img src="/images/Btn_agregar_producto2.png" width="126" height="160" alt="Agregar Venta">
                    </a>
                    <a   href="/administrador/agregarpublicacion"  target="_self">
                        <img src="/images/Btn_agregar_publicacion2.png" width="126" height="160" alt="Agregar publicacion">
                    </a>
                    <a   href="/administrador/verreservas" rel="_blank" target="_self">
                        <img src="/images/Btn_ver_reservas.png" width="126" height="160" alt="ver reservas">
                    </a>

                </div>
            </div>
        </div>
    </div>
</div>
