<?php
$this->title = "Listado Menus";
$this->headTitle($this->title);
?>
<div id="enteo-page">
    <div id="ctn-content">
        <?php echo $this->render('left-admin.phtml') ?>
        <div class="center">
            <div>
                <p class="sidebar-title"><img src="/images/guardar.png"> Listado de Menus </p>
                <div class="diseñotablas">
                    <a href="/administrador/agregarmenu/" style="text-decoration:none"><button class="botonnaranjo orange" >Agregar</button></a>
                    <table cellspacing="10%" cellpadding="30%">
                        <tr align = center  BGCOLOR="ccff66">
                            <td width="2%"><font><u>Nombre</u></font></td>
                            <td width="2%"><font><u>Descipcion</u></font></td>                    
                            <td width="2%"><font><u>Tipo Menu</u></font></td>
                            <td width="2%"><font><u>&nbsp;</u></font></td>
                            <td width="2%"><font><u>&nbsp;</u></font></td>
                        </tr>
                        <?php if (count($this->paginator)) : ?>
                            <?php foreach ($this->paginator as $res): ?>
                                <tr align="center" bgcolor="ffff99" >
                                    <td width="2%"><?php echo $res->nombre; ?></td>
                                    <td width="2%"><?php echo $res->descripcion; ?></td>
                                    <td width="2%"><?php echo $res->nombre_tipo; ?></td>
                                    <td align="2%"><a href="/administrador/editarmenus/id/<?php echo $res->id_producto ?>"><button class="buttonedit">Editar</button></a></td>
                                    <td align="2%"><a href="/administrador/borrarmenus/id/<?php echo $res->id_producto ?>"><button class="buttonedit" onclick="if (confirm('¿Esta seguro de eliminar?')) { document.location = '/administrador/borrarmenus/id/<?php echo $res->id_producto ?>'; } return false;" class="buttonedit">Borrar</button></a></td>
                                <?php endforeach; ?>
                            </tr>
                        <?php else : ?>
                            <tr>
                                <td colspan="3">No hay Datos</td>
                            </tr>

                        <?php endif; ?>

                    </table>
                    <?php if (count($this->paginator)): ?>
                        <?php echo $this->paginator; ?>
                    <?php endif; ?>

                </div>

            </div>
        </div>
    </div>
</div>
