<?php
$this->title = "Ventas Por Cliente";
$this->headTitle($this->title);
?>
<div id="enteo-page">
    <div id="ctn-content">
        <?php echo $this->render('left-admin.phtml') ?>

        <div class="center">

            <p class="sidebar-title">
                <img src="/images/guardar.png">
                Buscar Cliente
            </p>
            <?php echo $this->form;?>

        </div>
    </div>
</div>
