<?php
$this->title = "Listado Ventas";
$this->headTitle($this->title);
?>
<div id="enteo-page">
    <div id="ctn-content" style="height: 750px">
        <?php echo $this->render('left-admin.phtml') ?>
        <div class="center">
            <div id="ctn-slider">
                <p class="sidebar-title"><img src="/images/guardar.png"> Listado de Ventas </p>
                <div class="diseñotablas" style="margin-left: 5px">
                    <table style="width: 750px;" cellpadding="30%">
                        <tr align = center  BGCOLOR="ccff66">
                            <td width="2%"><font><u>Cliente</u></font></td>
                        <td width="2%"><font><u>Fecha</u></font></td>
                        <td width="1%"><font><u>Mesa</u></font></td>
                        <td width="2%"><font><u>Observacion</u></font></td>
                        <td width="2%"><font><u>Puntos Venta</u></font></td>
                        <td width="2%"><font><u>Total Venta</u></font></td> 
                        <td width="2%"><font><u></u></font></td>                                                                          

                        </tr>
                        <?php if (count($this->paginator)) : ?>
                            <?php foreach ($this->paginator as $res): ?>
                                <tr align="center" bgcolor="ffff99" >
                                    <td width="2%"><?php echo $res->cliente . ' ' . $res->apellido; ?></td>
                                    <!--                                    /* Conversion de Fecha */-->
                                    <?php
                                    $date = $res->fecha;
                                    $dia = explode("-", $date, 3);
                                    $year = $dia[0];
                                    $month = (string) (int) $dia[1];
                                    $day = (string) (int) $dia[2];
                                    $time = explode(":", $date, 3);
                                    $hora = explode(" ", $time[0], 2);
                                    $min = (string) (int) $time [1];
                                    $min2 = str_pad((int) $min, 2, "0", STR_PAD_LEFT)
                                    ?>
                                    <td width="2%"><?php echo $day . " - " . $month . " - " . $year . " " . "/" . " " . $hora[1] . ":" . $min2; ?></td>
                                    <td width="1%"><?php echo $res->mesa; ?></td>
                                    <td width="2%"><?php echo $res->observacion; ?></td>
                                    <td width="2%"><?php echo $res->puntos_venta; ?></td>
                                    <td width="2%"><?php echo $res->total; ?></td>
                                    <td width="2"><a href="/administrador/borrarventa/id/<?php echo $res->id_venta ?>"><button  class="buttonedit">Borrar</button></a></td>
                                <?php endforeach; ?>
                            </tr>
                        <?php else : ?>
                            <tr>
                                <td colspan="3">No hay Datos</td>
                            </tr>
                        <?php endif; ?>
                    </table>
                    <?php if (count($this->paginator)): ?>
                        <?php echo $this->paginator; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
