<div class="left">
    <div class="menu">
        <ul>
            <li><a href="/administrador">Administracion</a></li>
            <li>
                <a href="#"><span></span>Gestion de Ventas</a>
                <ul>
                    <li><a href="/administrador/agregarventa">Agregar Venta</a></li>
                    <li><a href="/administrador/verventas">Listar Ventas</a></li>
                    <li><a href="/administrador/ventacliente">Listar Ventas por Cliente</a></li>
                </ul>
            </li>
            <li>
                <a href="#">Gestion de Usuarios</a>
                <ul>
                    <li><a href="/administrador/agregarcliente">Agregar Cliente</a></li>
                    <li><a href="/administrador/listarclientes">Ver Clientes</a></li>
                    <li><a href="/administrador/agregaradministrador">Agregar Administrador</a></li>
                    <li><a href="/administrador/listaradministradores">Ver Administradores</a></li>
                </ul>
            </li>
            <li>
                <a href="#">Gestion de Menu</a>
                <ul>
                    <li><a href="/administrador/agregarmenu">Crear un Menu </a></li>
                    <li><a href="/administrador/listarmenus">Listar Menus</a></li>
                </ul>
            </li>
            <li>
                <a href="#"><span></span>Gestion de Productos</a>
                <ul>
                    <li><a href="/administrador/agregarproducto">Crear un producto</a></li>
                    <li><a href="/administrador/listarproductos">Listar Productos</a></li>
                </ul>
            </li>
            
            <li>
                <a href="#"><span></span>Gestion de Publicación</a>
                <ul>
                    <li><a href="/administrador/agregarpublicacion"> Hacer Publicacion</a></li>
                    <li><a href="/administrador/listarpublicaciones"> Listar Publicaciones</a></li>
                    

                </ul>
            </li>			
            	
            <li>
                <a href="/reportes">Reportes</a>
                
            </li>
            <li>
                <a href="#">Gestion Sistema</a>
                <ul >
                    <li><a href="/administrador/agregartipoproducto">Agregar Tipo Producto</a></li>                
                    <li><a href="/administrador/listartipoproductos">Listar Tipo Productos</a></li>
                     <li><a href="/administrador/agregartipopublicacion">Agregar Tipo Publicacion</a></li>
                     <li><a href="/administrador/listartipopublicaciones">Listar Tipo Publicaciones</a></li>
                    <li><a href="/administrador/envioemailmasivo">Envio de email masivo</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>