<div class="left">
    <div class="menu">
        <ul>
            <li><a href="/usuario">Inicio</a></li>
            <li>
                <a href="/usuario/editarperfil">Editar Perfil</a>             
            </li>
            <li>
                <a href="#"><span></span>Reservas</a>
                <ul>
                    <li><a href="/usuario/hacerreserva">Hacer Reserva</a></li>
                    <li><a href="/usuario/verreservas">Estado Reservas</a></li>
                </ul>
            </li>
            <li>
                <a href="/usuario/vercompras"><span></span>Ver Compras</a>
            </li>   
        </ul>
    </div>
</div>