<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
			<html xmlns='http://www.w3.org/1999/xhtml'> 
				<head> 
					<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
				</head>
				<div id='wrap' style='font-family:Arial, Helvetica, sans-serif; border:thick solid #ebebeb; background-color:#fafafa; width: 660px; height: auto; margin:auto;
				text-align:center;text-align : justify; position:left;'> 
					<div id='header' style='width: 660px; height: 100px; margin:auto; text-align:center; font-size:24px; display:block;'>
						<img src='http://capicua-restobar.cl/images/logo.png' />
					</div>
					<div id='texto' style='width:610px; text-align : justify; margin: 20px 10px 10px 20px;'>
						<h2 style='color:'#BF1515''>¡Saldos Estimado!</h2>
						<h2 style='color=#0101DF'>Tenemos Nuevas Noticias que Compartir</h2>
						<h2> <?php echo $this->mensaje; ?></h2><br><br><br><br>
						
					</div><!--fin texto-->
					<br/>
					<div id='footer' style='width: 660px; text-align:center; text-align : justify;'>
						<p style='color:#333;'>Contactenos Nuestra pagina web es : </p>
						<p>www.capicua-restobar.cl</p>
                        <p>Nuestro correo electronico es:</p>
						<p>capicua.contacto@gmail.com</p>
                         <p>Ubiquenos en la direccion San Antonio #1085, Viña del Mar</p>
					</div><!--fin footer-->
				</div> <!--fin wrap-->
			</html>






