<?php
$this->title = "Publicaciones";
$this->headTitle($this->title);
?>
<div id="enteo-page">
    <div id="ctn-content">
        <center>
            <a href="" rel="_blank" target="_self">
                <img src="/images/publicaciones.png" width="750" height="100" alt="menus">
            </a>
        </center>
        <div class="center">
            <?php if (count($this->paginator)): ?>
                <?php
                foreach ($this->paginator as $pub) :
                    $id_publicacion_1 = $pub->id_publicacion;
                    ?>
                    <div class="postg">
                        <div class="ribbon-wrapper-green">
                            <div class="ribbon-green"><?php echo $pub->nombre_tipo ?></div>
                        </div>
                        <div class="fecha">
                            <?php
                            /* Conversion de Fecha */
                            $date = $pub->fecha_publicacion;
                            $dia = explode("-", $date, 3);
                            $year = $dia[0];
                            $month = (string) (int) $dia[1];
                            $day = (string) (int) $dia[2];
                            $dias = array("domingo", "lunes", "martes", "mi&eacute;rcoles", "jueves", "viernes", "s&aacute;bado");
                            $tomadia = $dias[intval((date("w", mktime(0, 0, 0, $month, $day, $year))))];
                            $meses = array("", "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre");
                            echo '</br>';
                            ?>
                            <h2><?php echo $tomadia . ", " . $day . " de " . $meses[$month] . " de " . $year; ?></h2>
                        </div>
                        <div>
                            <img  src="/images/publicaciones/<?php echo $pub->imagen; ?>" alt="foto" class="imagenpublicacion" >
                        </div>
                        <div class="titulopublicacion" >
                            <p><?php echo $pub->titulo; ?></p>
                        </div>
                        <?php
                        $vigencia = $pub->fecha_vigencia;
                        $dia2 = explode("-", $vigencia, 3);
                        $year2 = $dia[0];
                        $month2 = (string) (int) $dia2[1];
                        $day2 = (string) (int) $dia2[2];
//                    $dias = array("domingo", "lunes", "martes", "mi&eacute;rcoles", "jueves", "viernes", "s&aacute;bado");
                        $tomadia2 = $dias[intval((date("w", mktime(0, 0, 0, $month2, $day2, $year2))))];
//                    $meses = array("", "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre");
                        ?>
                        <div class="contenidopublicacion">
                            <p><?php echo $pub->contenido; ?></p>
                        </div>
                        <div class="tagggs">
                            <ul class="tags">
                                <li><a href="">Hecho por: <?php echo $pub->nombre ?></a></li>
                                <li><a href="">Vigencia:<?php echo $tomadia2 . " " . $day2 . " de " . $meses[$month2] . " del " . $year2; ?></a></li>

                            </ul>
                        </div>
                        <div class="MBT-readmore"><a  href="/publicaciones/post/nn/<?php echo $pub->id_publicacion; ?>"  > Ver Mas >> </a></div>
                    </div>

                <?php endforeach; ?>                
            <?php else : ?>
                <p>No hay Publicaciones</p>
            <?php endif; ?>


            <?php if (count($this->paginator)): ?>
                <?php echo $this->paginator; ?>
            <?php endif; ?>

        </div>
        <div class="right">
            <?php echo $this->render('/banner/banner.phtml') ?>

        </div>


    </div>
</div>

