<?php
$this->headLink()->appendStylesheet('/bootstrap/css/bootstrap.css');
$this->headLink()->appendStylesheet('/css/style.css');
$this->headScript()->appendFile('/bootstrap/js/bootstrap.js');

$this->title = "Carta de Productos";
$this->headTitle($this->title);
?>
<?php $i = 1 ?>
<div>
    <center>
        <a href="" rel="_blank" target="_self">
            <img src="/images/carta_carta.png" width="750" height="100" alt="menus">
        </a>
    </center>

</div>
</br></br>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">   
            <div class="tabbable" id="tabs-423523" >
                <ul class="nav nav-tabs">
                    <?php foreach ($this->nombrestipo as $nombre): ?>
                        <?php
                        if ($i == 1) {
                            echo "<li class='active'><a href='#panel-" . $i . "' data-toggle='tab'>" . $nombre['nombre_tipo'] . "</a></li>";
                        } else {
                            echo "<li><a href='#panel-" . $i . "' data-toggle='tab'>" . $nombre['nombre_tipo'] . "</a></li>";
                        }
                        $i++;
                    endforeach;
                    ?>
                </ul>
                <div class="tab-content">
                    <?php $i = 1; ?>
                    <?php foreach ($this->nombrestipo as $nombre): ?>
                        <?php if ($i == 1) { ?>
                            <div class="tab-pane active" id="panel-<?php echo $i ?>">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>
                                                Nombre
                                            </th>
                                            <th>
                                                Descripcion
                                            </th>
                                            <th>
                                                Precio
                                            </th>
                                            <th>
                                                Imagen
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if (count($this->cartaproductos)) : ?>
                                            <?php foreach ($this->cartaproductos as $car): ?>
                                                <?php if ($car->id_tipo_producto == $nombre['id_tipo_producto']): ?>
                                                    <tr>
                                                        <td ><?php echo $car->nombre; ?></td>
                                                        <td><?php echo $car->descripcion; ?></td>
                                                        <td ><?php echo '$' . $car->precio; ?></td>
                                                        <td ><a href="/images/carta/<?php echo $car->imagen; ?>" rel="lightbox" title="<?php echo $car->nombre; ?>"><img src="/images/carta/<?php echo $car->imagen; ?>" alt="foto" class="fotocarta"> </a>
                                                    </tr>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                    </tbody>
                                </table>
                            </div>
                        <?php } else { ?>
                            <div class="tab-pane" id="panel-<?php echo $i ?>">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>
                                                Nombre
                                            </th>
                                            <th>
                                                Descripcion
                                            </th>
                                            <th>
                                                Precio
                                            </th>
                                            <th>
                                                Imagen
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if (count($this->cartaproductos)) : ?>
                                            <?php foreach ($this->cartaproductos as $car): ?>
                                                <?php if ($car->id_tipo_producto == $nombre['id_tipo_producto']): ?>
                                                    <tr>
                                                        <td><?php echo $car->nombre; ?></td>
                                                        <td><?php echo $car->descripcion; ?></td>
                                                        <td ><?php echo '$' . $car->precio; ?></td>
                                                        <td ><a href="/images/carta/<?php echo $car->imagen; ?>" rel="lightbox" title="<?php echo $car->nombre; ?>"><img src="/images/carta/<?php echo $car->imagen; ?>" alt="foto" class="fotocarta"> </a>
                                                    </tr>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                    </tbody>
                                </table>
                            </div>
                            <?php
                        }
                        $i++;
                    endforeach;
                    ?>                    
                </div>
            </div>
        </div>
    </div>
</div>