<div class="div_footer">
    <div class="cintafooter">
        <img src="/images/top_footer.jpg"  alt="footer" />
    </div>
    <div class="footer">
        <div class="contenidofooter">
            <h2>Contactenos</h2>
            <center style="margin-left: 50px; margin-top: -10px"><p> Nuestra pagina web es   :     www.capicua-restobar.cl</p></center>
            <center style="margin-left: 50px; margin-top: -10px"><p>Nuestro correo electronico es:      capicua.contacto@gmail.com  </p></center>
            <h2>Ubiquenos en la direccion </h2>
            <center style="margin-left: 50px; margin-top: -10px"><p>San Antonio #1085, Viña del Mar </p></center> 
        </div>
        <div class="nubes_footer"></div>
    </div>
</div>

