
<ul id="ctn-navigation">
    <li class="first">
        <a href="/index" class="active" title="Inicio">
            <img src="<?php echo $this->baseUrl();?>/images/inicio.png">  
        </a>
    </li>
    <li>
        <a href="/cartaproductos/mostrarmenu" title="Menu">Menu</a>
    </li>
    <li>
        <a href="/publicaciones" title="Promociones"> Publicaciones</a>
    </li>
    <li>
        <a href="/cartaproductos" title="Carta de Productos">Carta de Productos</a>
    </li>
    <li>
        <a href="/contacto" title="Contacto">Contáctanos</a>
    </li>
</ul>